[tool.poetry]
name = "mylib"
version = "0.2.0"
description = ""
authors = ["Marc-André Bühler <git@codezombie.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
